Feat/apiserver
kubesphere/kubeeye pull request #145
Opened 2022-03-01 11:21 UTC by panzhen6668

add apiserver for web  https://github.com/kubesphere/kubeeye/issues/142

/cc @pixiake @ruiyaoOps  @zheng1

2022-03-01 13:14 UTC, zheng1 commented
It is not recommended to put vendor in the committed code

2022-03-01 13:18 UTC, zheng1 commented
I see that there are a lot of code that will not be used at the moment, can we remove it for now?

2022-03-01 13:19 UTC, zheng1 requested changes

2022-03-01 13:19 UTC, zheng1 commented on pkg/utils/sets/byte.go
> +/*
If these codes are not used for the moment, you can delete them first

2022-03-01 13:19 UTC, zheng1 commented on pkg/apiserver/request/requestinfo.go
> +func (r *RequestInfoFactory) NewRequestInfo(req *http.Request) (*RequestInfo, error) {
This part of the logic should not be used, for now, so you can remove it.

2022-03-02 07:51 UTC, panzhen6668 commented
Resubmit  a Pr

2022-03-02 08:05 UTC, panzhen6668 commented
Resubmit a Pr

2022-03-02 08:07 UTC, panzhen6668 commented
add apiserver for web  https://github.com/kubesphere/kubeeye/issues/142 
simplify apiserver
/cc @pixiake @ruiyaoOps  @zheng1

2022-03-02 15:02 UTC, zheng1 commented
/approve

2022-03-02 15:03 UTC, merged

2022-03-07 07:55 UTC, pixiake commented
@all-contributors please add @panzhen6668  for code